import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import "./reset.css";
import QueryProvider from "@/app/provider";
import Link from "next/link";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
      <body className={`${inter.className} max-w-[1200px] min-w-[500px] ml-auto  mr-auto`} >
      <section>
        <div className={"text-center text-[40px] mb-3"}>
          <Link href={"/"}>포켓몬 도감</Link>
        </div>
      </section>
      <section>
        <QueryProvider>
          {children}
        </QueryProvider>
      </section>
      </body>
      </html>
  );
}
